### ISSUE TITLE
Review issues

### ISSUE THREAD

**Issue by robinwhittleton** [vr8hub/edward-gibbon_the-history-of-the-decline-and-fall-of-the-roman-empire#1]
**Overall**
- [x] en-GB? zero “colour” to 206 “color”, 4 “honour” to 1521 “honor”, 4 “labour” to 765 “labor“, 2 “harbour” to 145 “harbor”, 1 “behaviour” to 93 “behavior”, 
- [x] `xml:lang="xx-latn"` all need to be `xml:lang="xx-Latn"` (note capital letter). This is now checked with the latest lint.
- [x] Timeline spans need a space after to make sure they read correctly with a screenreader.
- [x] Run build-title again, as we now add roman semantics to `<title>` elements

**content.opf**
- [x] `<meta property="display-seq" refines="#illustrator">0</meta>` does what?
- [x] David Widger should have a nacoaf authority entry

**local.css**
- [x] <s>Missing `figure` styling: https://standardebooks.org/manual/1.6.4/single-page#7.8.5.2 . It’s in `figure.full-page`, but it’s probably worth keeping the standard styles in place so that they’re more easily upgraded in future if needed.</s>

**preface-1**
- [ ] “The chief works” should probably be an `<ol>` with `list-style-type: upper-roman`.
- [x] <s>“The editor’s notes are marked `<i epub:type="z3998:grapheme">M.</i>`”, then later “distinguished by the signature `<abbr epub:type="z3998:surname">`M.`</abbr>` 1845.” First should be an abbr surname too right?</s>

**preface-2**
- [ ] The “three following periods” should probably be an `<ol>` with `list-style-type: upper-roman`.
- [x] <s>Should we have footers for the Bentinck Street sections?</s>

**preface-4**
- [x] <s>`authlocation` classes would typically just be a para in a footer. But the structure isn’t immediately obvious.</s>
- [ ] “two `<em>`verbal`</em>` remarks” could be an `<ol>`

**chapter-8**
- [x] `xml:lang="fa"` should be `xml:lang="fa-Latn"`

**chapter-10**
- [x] `IV` needs roman semantics

**chapter-20**
- [x] `of»cross in` doesn’t appear in the scans, not sure where it’s come from.

**chapter-21**
- [x] `I` needs roman semantics

**chapter-40**
- [x] `V` needs roman semantics

**chapter-43**
- [ ] Should the conclusion be an `<ol>` with `list-style-type: upper-roman`? That way the custom styling could be removed.

**chapter-46**
- [x] `xml:lang="fa"` should be `xml:lang="fa-Latn"`

**chapter-47**
- [x] `xml:lang="syc"` should be `xml:lang="syc-Latn"`

**chapter-65**
- [x] `xml:lang="fa"` should be `xml:lang="fa-Latn"`
- [x] `xml:lang="mn"` should be `xml:lang="mn-Latn"`

**chapter-68**
- [x] `xml:lang="ar"` should be `xml:lang="ar-Latn"`
- [x] `xml:lang="fa"` should be `xml:lang="fa-Latn"`

**appendix**
- [x] Should these images have `se:image.color-depth.black-on-transparent` for dark mode?

**colophon**
- [x] `<b class="name">` is more recently `<b epub:type="z3998:personal-name">`

**endnotes**
- [x] 34: “The Coming of the Hungarians” should be marked up with span name.publication.paper
- [x] 210: Leipsic is converted by modernize-spelling to Leipzig
- [x] 213: I think the reference to “Laocoön” is the statue, so should be italicised with name.visual-art.statue
- [x] 534: `xml:lang="syc"` should be `xml:lang="syc-Latn"`
- [x] 692: `xml:lang="fa"` should be `xml:lang="fa-Latn"`
- [x] <s>1183: “de l’Abbé de La Bléterie à la `<i epub:type="se:name.publication.book" `xml:lang="fr"`>Germanie</i>` de Tacite” should all be French</s>
- [ ] <s>3228: Gengis -> Genghis courtesy of modernize-spelling</s>
- [x] 3231: 1825-1826 should use a en-dash as a date range https://standardebooks.org/manual/1.6.4/single-page#8.7.7.5
- [x] 3231: “F. H. Müller” needs some abbrs
- [x] 4161: Leipsic is converted by modernize-spelling to Leipzig
- [x] 4822: S. needs an abbr (not sure if there’s additional semantics)
- [ ] 4881: Is “DDNN” an abbreviation?
- [x] 7471: `xml:lang="ar"` should be `xml:lang="ar-Latn"`
- [x] 5817: `xml:lang="fa"` should be `xml:lang="fa-Latn"`
- [x] 5963: `xml:lang="syc"` should be `xml:lang="syc-Latn"`
- [x] 6121: Can we add an [Editorial] `<thead>` for accessibility?
- [x] 6121: Can the total be in a `<tfoot>`?
- [x] 6187: `xml:lang="frc"` should presumably be `xml:lang="grc"`?
- [x] 6777: `xml:lang="fgr"` should presumably be `xml:lang="fr"`?
- [x] 7290: Last two `<th>`s have Roman numerals that aren’t marked up
- [x] 7878: `xml:lang="mn"` should be `xml:lang="mn-Latn"`
- [x] 7926: I think the G. is a given name (George)
- [x] 8267: `xml:lang="fa"` should be `xml:lang="fa-Latn"`
- [ ] 8584: These should be `<ol>`s.
- [x] 8692: Can we add an [Editorial] `<thead>` for accessibility?
- [x] 8692: Can the total be in a `<tfoot>`? That way you could remove the nth-child border and select on tfoot instead.
- [x] <s>8839: “LXX” should presumably have roman semantics, even if it’s a Biblical reference.</s>
- [x] <s>8845: “LXX” should presumably have roman semantics, even if it’s a Biblical reference.</s>
- [x] 8911: `xml:lang="syc"` should be `xml:lang="syc-Latn"`
- [x] <s>9012: “Quarterly Review” is marked up as a journal in other places</s>
- [x] <s>9077: “LXX” should presumably have roman semantics, even if it’s a Biblical reference.</s>
- [x] 9182: A. is a given name
- [x] 9267: `xml:lang="fa"` should be `xml:lang="fa-Latn"`

**Comment by vr8hub** [comment]
Hah, no problem, I feel your pain—I took a week-and-a-half to review _Plato_, and I added issues the whole time. And thanks for your usual thoroughness—I feel like I've looked at this thing too long at this point. :)

(I haven't pushed the changes yet.)

- en-GB/US—I read three different editions while I was working on this, and while I noticed that some of the Britishisms were different in the Milman, I thought it was just some of them. But now that I look I see that it was published in Philadelphia. Doh!

- Timeline spans need a space where? Inside the `<span>` or outside? IOW,
```
<p><span class="timeline"><abbr epub:type="se:era">AD</abbr> 276 </span>All that had yet
```
or
```
<p><span class="timeline"><abbr epub:type="se:era">AD</abbr> 276</span> All that had yet
```

Presumably the former, because the latter will throw off the look of the rest of the text, right? IOW, the first line would be " All".

- Re display-seq, see the last discussion in the Gibbon thread on list; it prevents the illustrator from being included in the ID, title page, etc.

- local.css—not sure what you're saying here. I do have the figure CSS.

- All the `<ol>` mentions: I asked about this early on, because I was going to convert all of them throughout, but Alex said leave them. I actually bent that in endnotes for instances where the lists were numbered _and_ structurally subsidiary to the main paragraph, rather than being at the same level with them. Where the numbered (roman or no) sections are at the top-level, I did not convert any of them. I'm happy to do so (it's why I asked originally), but it doesn't make sense to do some and not all. 

- I marked the G. as grapheme because I read it as him saying, "Those notes are marked with a [letter] gee", so in that case, it is a letter. Where it is actually used as a signature, it's a name abbreviation.

- Re footers in preface-2 and -4, we can only have one footer per element, and there's only one element.

- Re -1183, I don't think so. We don't tag names, and "à la" is in M-W.

- Re -3228, I left Gengis as is because he immediately follows it with Zingis, so he's comparing two ways of referring to the name, neither of which is the modern one. It wouldn't make sense (to me) to change the first one to be the modern one. (He references in a later note why he uses Zingis throughout, which is why I didn't change them, either.)

- Re Leipsic (-4161), I intentionally left those, because they are part of book references. I treated all of the place names that are in the references just like the book titles themselves, and left everything as is.

- Re the DDNN (-4881), I don't know. Of a sort, I guess, but it's not an initialism, so I don't know how we would treat it.

- Re "thead for accessibility," I don't know what you mean by that.

- Re tfoots, I guess they could be, but we generally don't do that elsewhere. (There are a few, but they are the exception, not the rule.)

- Re Quarterly Review (-9012), the actual Quarterly Review reference is a few words later, after the title, and that one is tagged. I read that first one as more of a generic reference, i.e. a stand-in for "article—"from the article of Beugnot". I was ambivalent about it at the time, though, so I could probably be talked into it. :)

- Re LXX, no, I don't believe it should. If anything it's a special-case initialism—it's the name, pronounced ell-ex-ex, not Seventy.

**Comment by vr8hub** [comment]
Forgot one…

Re the images and .transparent, the manual says "…image is black-on-white line art…are PNG files with a transparent background." These are not line art and are not PNG files. So I don't _think_ so.

**Comment by robinwhittleton** [comment]
Closest is Ulysses S. Grant’s maps, which do have the semantic: https://github.com/standardebooks/ulysses-s-grant_personal-memoirs-of-ulysses-s-grant/blob/master/src/epub/text/maps.xhtml . As for the rest, sounds like you’ve got this all in hand generally 🙂 To answer a few questions:

- Timeline spans: outside the span. As they’re floated the space would appear.
- local.css: you’ve got the right rules, but they don’t match the setup from the manual. But it’s a minor point, and doesn’t need to be actioned.
- thead for accessibility: I mean that the table as stands doesn’t have any headers. If you’re using a screen reader and trying to navigate it in tables-mode (typically arrow keys) then the cells’ headers won’t be read out as highlighted because there are none. But it’s not immediately obvious what the middle one would be, and I’d be happy if you decided not to do this.

**Comment by vr8hub** [comment]
Re the maps… Interesting. Well, there are only four, I'll go ahead and add it. I didn't originally because of the manual section I quoted, but David knows a thousand times more than I do about illustrations. If it's wrong, it's easy for Alex to drop the commit.

Re the timelines: urgh. Isn't that going to do what I said, i.e. put a space at the front of  the paragraphs where the spans are first? That's not going to look good. I guess I should try it and see…

Re the image CSS, I just it checked it again,  and I _think_ I see what you mean. I used the CSS from the "Examples" in [7.8.5.4](https://standardebooks.org/manual/1.6.4/single-page#7.8.5.4), which has the `break-inside` inside the full-page section. And since I don't have any that aren't full-page, I didn't include the standalone, for the same reason we don't include other non-used CSS.

Re the table headers: Interesting. I know nothing about readers and don't know anyone who uses one, so this is an honest if ignorant (lack of knowledge) question: Is it more difficult for someone using a reader to pick up the contents from context (text before and/or after, contents)?
I'm happy to do this, it just never occurred to me (aforementioned lack of knowledge, bias against adding things to the text, etc.).
For -6121, I used "# Campagns" (actually, as I'm typing that, will that be read correctly on a reader, i.e. as "Number campaigns"? I was trying to minimize the width since it's just one or two digits for the contents) for the first and "People Group" for the last ("Country" or "Nation" doesn't really work there since there are things like "Saracens in Italy").
For -8692 I used "Country" and "Population".

**Comment by vr8hub** [comment]
I tried adding a space after a handful in chapter 8, and I don't _see_ any difference, so maybe that will work. I guess I'll add them, but not gonna lie, it makes me nervous.

**Comment by robinwhittleton** [comment]
Yeah, there won’t be a problem with the space, it’s how floats work.

**Comment by vr8hub** [comment]
You said "name.visual-art.statue" above, but there isn't such a thing (I just ran lint in preparation for pushing all the changes). Did you mean "sculpture"? I guess those are interchangeable, at least for the time period.

**Comment by vr8hub** [comment]
I'm assuming that is the case, so went ahead and made the change. I've pushed everything up; lint shows clear (I updated to latest tools HEAD before running). Let me know what else you find!

**Comment by robinwhittleton** [comment]
Sure, I’ll give it another runthrough this week and see if anything else jumps out. After that I think it’ll be time for Alex to cast his eye over it.

**Comment by vr8hub** [comment]
Leipsic and Frankfort updated and pushed per discussion on list.
